### ISSUE TITLE
Checking counterpoint to be included?

### ISSUE THREAD

**Issue by xhevahir** [rogerioConstante/plugin-harmonia#1]
Will this plugin eventually include functions that apply counterpoint rules? Or maybe that is planned for another plugin? Thank you for this plugin, by the way.

**Comment by rogerioConstante** [comment]
Hi, i'm working in a specific plugin to check counterpoint rules. I'll be uploading it in few days.
Thanks,
Rogério.


________________________________
De: xhevahir <notifications@github.com>
Enviado: sexta-feira, 20 de setembro de 2019 11:19
Para: rogerioConstante/plugin-harmonia <plugin-harmonia@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [rogerioConstante/plugin-harmonia] Checking counterpoint to be included? (#1)


Will this plugin eventually include functions that apply counterpoint rules? Or maybe that is planned for another plugin? Thank you for this plugin, by the way.

**Comment by rogerioConstante** [comment]
Hi,
a lot of days after...
https://github.com/rogerioConstante/Contraponto
